=== DouganRedhammer/Project2/artist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.cs.sjsu.edu/cs157b/Artist" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cs.sjsu.edu/cs157b/Artist">
	<xs:element name="artistname">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="artistid" type="xs:byte"/>
	<xs:element name="artistTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="artist" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="artist">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="artistid"/>
				<xs:element ref="artistname"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DouganRedhammer/Project2/artist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<artistTable xsi:schemaLocation="http://www.cs.sjsu.edu/cs157b/Artist artist.xsd" xmlns="http://www.cs.sjsu.edu/cs157b/Artist" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<artist>
		<artistid>1</artistid>
		<artistname>The Smashing Pumpkins</artistname>
	</artist>
	<artist>
		<artistid>2</artistid>
		<artistname>Nirvana</artistname>
	</artist>
		<artist>
		<artistid>3</artistid>
		<artistname>Stone Temple Pilots</artistname>
	</artist>
</artistTable>
