=== DouganRedhammer/Project2/composer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.cs.sjsu.edu/cs157b/Composer" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cs.sjsu.edu/cs157b/Composer">
	<xs:element name="composerName">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="composerId" type="xs:integer"/>
	<xs:element name="composerTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="composer" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="composer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="composerId"/>
				<xs:element ref="composerName"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DouganRedhammer/Project2/composer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<composerTable xsi:schemaLocation="http://www.cs.sjsu.edu/cs157b/Composer composer.xsd" xmlns="http://www.cs.sjsu.edu/cs157b/Composer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<composer>
		<composerId>4</composerId>
		<composerName>Robert DeLeo</composerName>
	</composer>
	<composer>
		<composerId>5</composerId>
		<composerName>Kurt Cobain</composerName>
	</composer>
	<composer>
		<composerId>6</composerId>
		<composerName>Billy Corgan</composerName>
	</composer>
</composerTable>
