=== DouganRedhammer/Project2/track.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns="http://www.cs.sjsu.edu/cs157b/Track" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cs.sjsu.edu/cs157b/Track">
	<xs:element name="trackTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="track" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="track">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="code"/>
				<xs:element ref="duration"/>
				<xs:element ref="trackName"/>
				<xs:element ref="trackComposer_id"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="trackName">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="duration">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="trackComposer_id" type="xs:integer"/>
	<xs:element name="code" type="xs:integer"/>
</xs:schema>

=== DouganRedhammer/Project2/track.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<trackTable xsi:schemaLocation="http://www.cs.sjsu.edu/cs157b/Track track.xsd" xmlns="http://www.cs.sjsu.edu/cs157b/Track" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<track>
		<code>8</code>
		<duration>3:23</duration>
		<trackName>Perfect</trackName>
		<trackComposer_id>3</trackComposer_id>
	</track>
	<track>
		<code>2</code>
		<duration>5:33</duration>
		<trackName>Creep</trackName>
		<trackComposer_id>1</trackComposer_id>
	</track>
	<track>
		<code>3</code>
		<duration>4:05</duration>
		<trackName>Wicked Garden</trackName>
		<trackComposer_id>1</trackComposer_id>
	</track>
	<track>
		<code>4</code>
		<duration>5:10</duration>
		<trackName>Dead &amp; Bloated</trackName>
		<trackComposer_id>1</trackComposer_id>
	</track>
	<track>
		<code>5</code>
		<duration>5:01</duration>
		<trackName>Smells Like Teen Spirit</trackName>
		<trackComposer_id>2</trackComposer_id>
	</track>
	<track>
		<code>6</code>
		<duration>3:39</duration>
		<trackName>Come as You Are</trackName>
		<trackComposer_id>2</trackComposer_id>
	</track>
	<track>
		<code>7</code>
		<duration>2:57</duration>
		<trackName>Polly</trackName>
		<trackComposer_id>2</trackComposer_id>
	</track>
</trackTable>
